@startuml
'!theme plain
!theme blueprint
skinparam BackgroundColor #000c18
'skinparam ClassBackgroundColor #000c18
skinparam linetype ortho

title Warehouse Class Diagram

class Warehouse{
    number: String
    owner: String
    address: String
    capacity: Integer
    storedItems: List<StoredItem>
    manager: WarehouseManager
    ..
    setOwner(String owner): void
    setCapacity(Integer value): void
    setManager(WarehouseManager manager): void
}
class Person{
    firstName: String
    LastName: String
    phone: String
    email: String
    ..
    setPhone(String phone): void
    setEmail(String email): void
}
class Manager{
    title: String
    company: String
    ..
    setTitle(String title): void
    setCompany(String company): void
}

class WarehouseManager{
    number: String
    startDate: LocalDate
}
class Item{
    number: String
    name: String
    description: String
    price: Integer
    group: Group
        ..
        setPrice(Integer value): void
        setGroup(Group group): void
        setDescription(String description): void
    }
class StoredItem{
    item: Item
    amount: Integer
    ..
    setAmount(Integer value): void
}
class Group {
    -subGroups: List<Group>
    -items: List<Item>
}
class WarehouseManagement{
    storeItem(Item item, amount Integer): void
    removeItem(Item item, amount Integer): void
    isItemStored(Item item): boolean
    getStoredItemCount(Item item): Integer
}
class GroupManagement{
    addSubGroup(Group group, Group subGroup): void
    removeSubGroup(Group group, Group subGroup): void
    addItemToGroup(Group group, Item item): void
    removeItemFromGroup(Group group, Item item): void
}

Person <|-u- Manager
Manager <|-u- WarehouseManager
Warehouse  o--  WarehouseManager
Warehouse o--  StoredItem
StoredItem o-- Item
Item o-r- Group
Warehouse <.. WarehouseManagement
Group <-- GroupManagement
Group o-- Group

legend
    The getters are omitted
    The setters shown only for non-final fields
endlegend

@enduml